# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a9f47ba4b97976adbb326c9b6c4b76acf9c827c31c1732946ce17cd6be06ee045237458a6bdaf50942e312f382b28d8595dd71f8d262ad7e322c0acbf8a3e8a2

test:
  secret_key_base: 130aa28abc2cdb04e48d8fef4f386f31eb0dd5892f8812e392e1d68a0eb2828b23175367df44d10b9e6421258815e0baa16bb67ac25de2b4ba793ae04a364037

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
